#Requires -Version 5.1
<#
.SYNOPSIS
  Interactive HZZS release signing setup and optional APK build.

.DESCRIPTION
  Prompts for keystore path / password / alias (password hidden),
  optionally writes gitignored keystore.properties,
  optionally runs: testDebugUnitTest lintRelease assembleRelease

  Usage (repo root):
    powershell -ExecutionPolicy Bypass -File tools\release\build_signed_release.ps1
    .\tools\release\build_signed_release.ps1 -SkipBuild
    .\tools\release\build_signed_release.ps1 -BuildOnly

  Do not commit real passwords or the keystore file.
#>
[CmdletBinding()]
param(
    [string]$StoreFile = 'D:\Azek431-Secrets\AndroidSigning\azek431-android-release.p12',
    [switch]$SkipBuild,
    [switch]$NoSaveProperties,
    [switch]$BuildOnly
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

function Get-RepoRoot {
    $here = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Path }
    return (Resolve-Path (Join-Path $here '..\..')).Path
}

function Read-SecretText {
    param([Parameter(Mandatory = $true)][string]$Prompt)
    $secure = Read-Host -Prompt $Prompt -AsSecureString
    $bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
    try {
        return [Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr)
    }
    finally {
        if ($bstr -ne [IntPtr]::Zero) {
            [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)
        }
    }
}

function Escape-JavaPropertiesValue {
    param([string]$Value)
    if ($null -eq $Value) { return '' }
    # Use String.Replace (not -replace regex) so backslash is literal
    return $Value.Replace([string][char]0x5C, '/')
}

$repoRoot = Get-RepoRoot
Set-Location $repoRoot
Write-Host ''
Write-Host '=== HZZS Release Signing Helper ===' -ForegroundColor Cyan
Write-Host ("Repo root: {0}" -f $repoRoot)
Write-Host 'Passwords are not echoed. Optional keystore.properties is gitignored.'
Write-Host ''

if (-not $BuildOnly) {
    $inputPath = Read-Host ("Keystore path [default: {0}]" -f $StoreFile)
    if (-not [string]::IsNullOrWhiteSpace($inputPath)) {
        $StoreFile = $inputPath.Trim().Trim('"')
    }

    if (-not (Test-Path -LiteralPath $StoreFile)) {
        throw ("Keystore not found: {0}" -f $StoreFile)
    }

    $storePassword = Read-SecretText -Prompt 'Store password (hidden)'
    if ([string]::IsNullOrWhiteSpace($storePassword)) {
        throw 'storePassword cannot be empty'
    }

    $keyAlias = Read-Host 'Key alias'
    if ([string]::IsNullOrWhiteSpace($keyAlias)) {
        throw 'keyAlias cannot be empty'
    }
    $keyAlias = $keyAlias.Trim()

    $sameKeyPass = Read-Host 'Use same password for keyPassword? [Y/n]'
    if ([string]::IsNullOrWhiteSpace($sameKeyPass) -or $sameKeyPass -match '^[Yy]') {
        $keyPassword = $storePassword
    }
    else {
        $keyPassword = Read-SecretText -Prompt 'Key password (hidden)'
        if ([string]::IsNullOrWhiteSpace($keyPassword)) {
            throw 'keyPassword cannot be empty'
        }
    }

    $env:ANDROID_KEYSTORE_PATH = $StoreFile
    $env:ANDROID_STORE_PASSWORD = $storePassword
    $env:ANDROID_KEY_ALIAS = $keyAlias
    $env:ANDROID_KEY_PASSWORD = $keyPassword
    $env:AZEK431_RELEASE_STORE_FILE = $StoreFile
    $env:AZEK431_RELEASE_STORE_PASSWORD = $storePassword
    $env:AZEK431_RELEASE_KEY_ALIAS = $keyAlias
    $env:AZEK431_RELEASE_KEY_PASSWORD = $keyPassword

    Write-Host ''
    Write-Host ("Session env set. path={0} alias={1}" -f $StoreFile, $keyAlias) -ForegroundColor Green

    if (-not $NoSaveProperties) {
        $save = Read-Host 'Write keystore.properties under repo root (gitignored)? [Y/n]'
        if ([string]::IsNullOrWhiteSpace($save) -or $save -match '^[Yy]') {
            $propsPath = Join-Path $repoRoot 'keystore.properties'
            $lines = @(
                '# Generated by tools/release/build_signed_release.ps1 - DO NOT COMMIT'
                ('storeFile={0}' -f (Escape-JavaPropertiesValue $StoreFile))
                ('storePassword={0}' -f $storePassword)
                ('keyAlias={0}' -f $keyAlias)
                ('keyPassword={0}' -f $keyPassword)
            )
            $content = ($lines -join [Environment]::NewLine) + [Environment]::NewLine
            $utf8NoBom = New-Object System.Text.UTF8Encoding $false
            [System.IO.File]::WriteAllText($propsPath, $content, $utf8NoBom)
            Write-Host ("Wrote: {0}" -f $propsPath) -ForegroundColor Green
            Write-Host 'Verify ignored: git check-ignore -v keystore.properties' -ForegroundColor Yellow
        }
    }
}
else {
    $hasEnv = -not [string]::IsNullOrWhiteSpace($env:ANDROID_KEYSTORE_PATH)
    $hasProps = Test-Path -LiteralPath (Join-Path $repoRoot 'keystore.properties')
    if (-not $hasEnv -and -not $hasProps) {
        throw 'BuildOnly needs existing env vars or keystore.properties. Run without -BuildOnly first.'
    }
    Write-Host 'BuildOnly: using existing env / keystore.properties' -ForegroundColor Cyan
}

if ($SkipBuild) {
    Write-Host ''
    Write-Host 'SkipBuild: signing configured only. Next:' -ForegroundColor Yellow
    Write-Host '  .\gradlew.bat --no-daemon :app:testDebugUnitTest :app:lintRelease :app:assembleRelease'
    exit 0
}

if ($BuildOnly) {
    $doBuild = 'Y'
}
else {
    $doBuild = Read-Host 'Run testDebugUnitTest + lintRelease + assembleRelease now? [Y/n]'
}

if (-not [string]::IsNullOrWhiteSpace($doBuild) -and $doBuild -match '^[Nn]') {
    Write-Host 'Signing ready, build skipped. Later:' -ForegroundColor Yellow
    Write-Host '  .\tools\release\build_signed_release.ps1 -BuildOnly'
    exit 0
}

$gradlew = Join-Path $repoRoot 'gradlew.bat'
if (-not (Test-Path -LiteralPath $gradlew)) {
    throw ("gradlew.bat not found: {0}" -f $gradlew)
}

Write-Host ''
Write-Host 'Starting Gradle release build...' -ForegroundColor Cyan
& $gradlew --no-daemon :app:testDebugUnitTest :app:lintRelease :app:assembleRelease
$code = $LASTEXITCODE
if ($code -ne 0) {
    throw ("Gradle failed with exit code {0}" -f $code)
}

$apk = Join-Path $repoRoot 'app\build\outputs\apk\release\app-release.apk'
if (Test-Path -LiteralPath $apk) {
    $item = Get-Item -LiteralPath $apk
    Write-Host ''
    Write-Host 'BUILD SUCCESS' -ForegroundColor Green
    Write-Host ("APK: {0}" -f $item.FullName)
    Write-Host ("Size: {0:N2} MB" -f ($item.Length / 1MB))
    Write-Host 'Package: top.azek431.hzzs'
    Write-Host 'Copy to phone to upgrade the release install (same signing cert required).'
}
else {
    Write-Host 'Build finished but app-release.apk was not found. Check Gradle output.' -ForegroundColor Yellow
}
