#!/usr/bin/env python3
"""Generate compile-time StripClassProfile tables for sea-salt scan-point patterns.

Source of truth:
  - tools/vision_v2/sea_baseline.py (AutoJs multicolor points, base 1272x2772)
  - tools/vision_v2/sea_fast_detector.py (scan point index + y band ratios)
  - tools/vision_v2/sea_polygons.json (canonical polygons + ext offsets)

Coordinates are stored in **design/base pixels**. Host detectors scale via
scale_strip_profile() before detect_fixed_strips. Frame path never parses JSON.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools" / "vision_v2"))

from sea_baseline import BASE_H, BASE_W, PATTERNS, int_to_rgb  # noqa: E402
from sea_fast_detector import SCAN_POINT_INDEX, SCAN_Y_RATIO, SCAN_Y_TOL  # noqa: E402

DEFAULT_JSON = ROOT / "tools" / "vision_v2" / "sea_polygons.json"
DEFAULT_OUT = ROOT / "app" / "src" / "main" / "cpp" / "vision_v2" / "generated" / "sea_profiles_v2.h"

MAX_POINTS = 8
MAX_POLYGON = 24
DEFAULT_REQUIRED_POINTS = 4

# Stable C++ order (skip 复活 — not in sea_fast scan set).
PROFILE_ORDER = (
    ("SEA_CLIFF_LARGE", "大断崖"),
    ("SEA_CLIFF_SMALL", "小断崖"),
    ("SEA_DUNE_LOW", "矮沙丘"),
    ("SEA_DUNE_HIGH", "高沙丘"),
    ("SEA_ANCHOR", "船锚"),
)


def cpp_float(value: float) -> str:
    text = f"{float(value):.6g}"
    if "e" in text or "E" in text:
        return f"{text}f"
    if "." not in text:
        text = f"{text}.0"
    return f"{text}f"


def argb_to_rgb(value: int) -> tuple[int, int, int]:
    arr = int_to_rgb(value)
    return int(arr[0]), int(arr[1]), int(arr[2])


def build_profile(cpp_name: str, cn_name: str, polygons_doc: dict) -> dict:
    first, points = PATTERNS[cn_name]
    all_points = [(0, 0, first), *list(points)]
    scan_index = int(SCAN_POINT_INDEX[cn_name])
    if scan_index < 0 or scan_index >= len(all_points):
        raise ValueError(f"{cn_name}: scan index out of range")
    if len(all_points) > MAX_POINTS:
        raise ValueError(f"{cn_name}: {len(all_points)} points > {MAX_POINTS}")

    ext = polygons_doc["ext"][cn_name]
    poly = polygons_doc["polygons"][cn_name]
    if len(poly) < 3:
        raise ValueError(f"{cn_name}: polygon needs >= 3 verts")
    if len(poly) > MAX_POLYGON:
        raise ValueError(f"{cn_name}: {len(poly)} verts > {MAX_POLYGON}")

    x0, y0 = float(ext[0]), float(ext[1])
    # Polygon verts relative to original AutoJs anchor (same origin as point (0,0)).
    poly_rel = [(float(v[0]) + x0, float(v[1]) + y0) for v in poly]

    xs = [p[0] for p in all_points] + [v[0] for v in poly_rel]
    ys = [p[1] for p in all_points] + [v[1] for v in poly_rel]
    min_x, max_x = min(xs), max(xs)
    min_y, max_y = min(ys), max(ys)
    # Origin may be slightly outside template bbox (negative points). full_* is extent
    # from origin (0,0) covering positive side; negative offsets still verified.
    full_w = max(1, int(round(max(max_x, 0) - min(min_x, 0))))
    full_h = max(1, int(round(max(max_y, 0) - min(min_y, 0))))

    expected_y = int(round(float(SCAN_Y_RATIO[cn_name]) * BASE_H))
    # row_tolerance in base pixels from ratio tol
    row_tol = max(4, int(round(float(SCAN_Y_TOL[cn_name]) * BASE_H)))

    return {
        "cpp_name": cpp_name,
        "cn_name": cn_name,
        "points": all_points,
        "scan_index": scan_index,
        "expected_y": expected_y,
        "row_tol": row_tol,
        "full_w": full_w,
        "full_h": full_h,
        "polygon": poly_rel,
        "required": min(DEFAULT_REQUIRED_POINTS, len(all_points)),
    }


def render_header(profiles: list[dict]) -> str:
    lines: list[str] = [
        "// AUTO-GENERATED by tools/vision_v2/generate_sea_profiles_inc.py",
        "// Sources: sea_baseline.py / sea_fast_detector.py / sea_polygons.json",
        "// Design space: 1272x2772. Scale with scale_strip_profile before detect.",
        "// Do not edit by hand.",
        "#pragma once",
        "",
        '#include "fast_contour_pipeline.h"',
        "",
        "#include <array>",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace hzzs::vision_v2 {",
        "",
        "enum class SeaProfileId : std::uint8_t {",
    ]
    for index, profile in enumerate(profiles):
        comma = "," if index + 1 < len(profiles) else ""
        lines.append(f"    {profile['cpp_name']} = {index}{comma}")
    lines += [
        "};",
        "",
        f"inline constexpr std::size_t kSeaProfileCount = {len(profiles)};",
        f"inline constexpr int kSeaBaseWidth = {BASE_W};",
        f"inline constexpr int kSeaBaseHeight = {BASE_H};",
        "",
        "inline constexpr std::array<const char*, kSeaProfileCount> kSeaProfileNames{{",
    ]
    for profile in profiles:
        lines.append(f'    "{profile["cpp_name"]}",')
    lines += [
        "}};",
        "",
        "inline constexpr std::array<const char*, kSeaProfileCount> kSeaProfileCnNames{{",
    ]
    for profile in profiles:
        lines.append(f'    "{profile["cn_name"]}",')
    lines += [
        "}};",
        "",
        "inline constexpr std::array<StripClassProfile, kSeaProfileCount> kSeaProfilesV2{{",
    ]

    for class_index, profile in enumerate(profiles):
        points = profile["points"]
        lines.append(f"    // {profile['cpp_name']} / {profile['cn_name']}")
        lines.append("    StripClassProfile{")
        lines.append(f"        /*class_index=*/{class_index},")
        lines.append(f"        /*point_count=*/{len(points)},")
        lines.append(f"        /*required_points=*/{profile['required']},")
        lines.append(f"        /*lut_point_index=*/{profile['scan_index']},")
        lines.append(f"        /*expected_y=*/{profile['expected_y']},")
        lines.append(f"        /*row_tolerance=*/{profile['row_tol']},")
        lines.append(f"        /*full_w=*/{profile['full_w']},")
        lines.append(f"        /*full_h=*/{profile['full_h']},")
        lines.append("        /*points=*/{{")
        for x, y, color in points:
            r, g, b = argb_to_rgb(color)
            lines.append(f"            TemplatePoint{{{int(x)}, {int(y)}, Rgb{{{r}, {g}, {b}}}}},")
        for _ in range(len(points), MAX_POINTS):
            lines.append("            TemplatePoint{},")
        lines.append("        }},")
        lines.append(f"        /*polygon_count=*/{len(profile['polygon'])},")
        lines.append("        /*polygon=*/{{")
        for x, y in profile["polygon"]:
            lines.append(f"            PointF{{{cpp_float(x)}, {cpp_float(y)}}},")
        for _ in range(len(profile["polygon"]), MAX_POLYGON):
            lines.append("            PointF{},")
        lines.append("        }},")
        lines.append("    },")

    lines += [
        "}};",
        "",
        "[[nodiscard]] inline constexpr std::size_t sea_profile_index(SeaProfileId id) noexcept {",
        "    return static_cast<std::size_t>(id);",
        "}",
        "",
        "}  // namespace hzzs::vision_v2",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--polygons", type=Path, default=DEFAULT_JSON)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    doc = json.loads(args.polygons.read_text(encoding="utf-8"))
    profiles = [build_profile(cpp, cn, doc) for cpp, cn in PROFILE_ORDER]
    text = render_header(profiles)

    if args.check:
        if not args.out.is_file():
            print(f"missing generated header: {args.out}", file=sys.stderr)
            return 1
        if args.out.read_text(encoding="utf-8") != text:
            print(f"generated header out of date: {args.out}", file=sys.stderr)
            print("run: python tools/vision_v2/generate_sea_profiles_inc.py", file=sys.stderr)
            return 1
        print(f"up to date: {args.out}")
        return 0

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {args.out} ({len(profiles)} profiles, base {BASE_W}x{BASE_H})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
