#!/usr/bin/env python3
"""Generate compile-time StripClassProfile tables from fixed_profiles_v2.json.

Frame path must never parse JSON. This tool runs at generate time (dev/CI),
writing a C++ header consumed by host smokes. It does not touch Android CMake.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_JSON = ROOT / "tools" / "vision_v2" / "fixed_profiles_v2.json"
DEFAULT_OUT = ROOT / "app" / "src" / "main" / "cpp" / "vision_v2" / "generated" / "fixed_profiles_v2.h"

# Match tools/vision_v2/fixed_strip_detector.py defaults.
DEFAULT_REQUIRED_POINTS = 4
DEFAULT_ROW_TOLERANCE = 7
# One LUT seed per class (first sparse point). Multi-seed slots can be added later.
DEFAULT_LUT_POINT_INDEX = 0

MAX_POINTS = 8
MAX_POLYGON = 24
MAX_CLASSES = 16

# Stable order for class_index.
PROFILE_ORDER = (
    "SWEET_SPIKE",
    "POISON_BOTTLE",
    "CAKE",
    "HANGING_BRUSH",
    "PANDA_STATUE",
)


def cpp_float(value: float) -> str:
    """Emit a C++ float literal that is always valid (digit.digitf)."""
    text = f"{float(value):.6g}"
    if "e" in text or "E" in text:
        # scientific: ensure float suffix works, e.g. 1.2e-3f
        return f"{text}f"
    if "." not in text:
        text = f"{text}.0"
    return f"{text}f"


def expected_scan_y(profile: dict, point_index: int) -> int:
    point = profile["points"][point_index]
    y = float(profile["expected_match_y"]) - float(profile["match_offset"][1]) + float(point["y"])
    return int(round(y))


def validate_profile(name: str, profile: dict) -> None:
    points = profile.get("points") or []
    polygon = profile.get("polygon") or []
    full = profile.get("full_size") or []
    if not points:
        raise ValueError(f"{name}: empty points")
    if len(points) > MAX_POINTS:
        raise ValueError(f"{name}: {len(points)} points > kMaxPoints={MAX_POINTS}")
    if len(polygon) > MAX_POLYGON:
        raise ValueError(f"{name}: {len(polygon)} polygon verts > kMaxPolygon={MAX_POLYGON}")
    if len(polygon) < 3:
        raise ValueError(f"{name}: polygon needs >= 3 vertices")
    if len(full) != 2 or int(full[0]) <= 0 or int(full[1]) <= 0:
        raise ValueError(f"{name}: invalid full_size")
    for i, point in enumerate(points):
        rgb = point["rgb"]
        if len(rgb) != 3:
            raise ValueError(f"{name}.points[{i}]: rgb must be 3 channels")
        for channel in rgb:
            if not 0 <= int(channel) <= 255:
                raise ValueError(f"{name}.points[{i}]: rgb out of range")


def render_header(data: dict) -> str:
    if len(PROFILE_ORDER) > MAX_CLASSES:
        raise ValueError("too many profiles for Rgb15Lut::kMaxClasses")

    lines: list[str] = [
        "// AUTO-GENERATED by tools/vision_v2/generate_fixed_profiles_inc.py",
        "// Source: tools/vision_v2/fixed_profiles_v2.json",
        "// Do not edit by hand. Re-run the generator after changing the JSON.",
        "#pragma once",
        "",
        '#include "fast_contour_pipeline.h"',
        "",
        "#include <array>",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace hzzs::vision_v2 {",
        "",
        "enum class FixedProfileId : std::uint8_t {",
    ]
    for index, name in enumerate(PROFILE_ORDER):
        comma = "," if index + 1 < len(PROFILE_ORDER) else ""
        lines.append(f"    {name} = {index}{comma}")
    lines += [
        "};",
        "",
        f"inline constexpr std::size_t kFixedProfileCount = {len(PROFILE_ORDER)};",
        "",
        "inline constexpr std::array<const char*, kFixedProfileCount> kFixedProfileNames{{",
    ]
    for name in PROFILE_ORDER:
        lines.append(f'    "{name}",')
    lines += [
        "}};",
        "",
        "// One StripClassProfile per class; lut seed = first sparse point",
        "// (fixed_strip_detector anchors_per_class>1 can be expanded later).",
        "inline constexpr std::array<StripClassProfile, kFixedProfileCount> kFixedProfilesV2{{",
    ]

    for class_index, name in enumerate(PROFILE_ORDER):
        if name not in data:
            raise KeyError(f"missing profile {name}")
        profile = data[name]
        validate_profile(name, profile)
        points = profile["points"]
        polygon = profile["polygon"]
        full_w, full_h = int(profile["full_size"][0]), int(profile["full_size"][1])
        lut_index = DEFAULT_LUT_POINT_INDEX
        required = min(DEFAULT_REQUIRED_POINTS, len(points))
        exp_y = expected_scan_y(profile, lut_index)

        lines.append(f"    // {name}")
        lines.append("    StripClassProfile{")
        lines.append(f"        /*class_index=*/{class_index},")
        lines.append(f"        /*point_count=*/{len(points)},")
        lines.append(f"        /*required_points=*/{required},")
        lines.append(f"        /*lut_point_index=*/{lut_index},")
        lines.append(f"        /*expected_y=*/{exp_y},")
        lines.append(f"        /*row_tolerance=*/{DEFAULT_ROW_TOLERANCE},")
        lines.append(f"        /*full_w=*/{full_w},")
        lines.append(f"        /*full_h=*/{full_h},")
        lines.append("        /*points=*/{{")
        for point in points:
            x, y = int(point["x"]), int(point["y"])
            r, g, b = (int(c) for c in point["rgb"])
            lines.append(
                f"            TemplatePoint{{{x}, {y}, Rgb{{{r}, {g}, {b}}}}},"
            )
        # pad remaining slots for readability (value-init rest via fewer entries is OK
        # for constexpr aggregate if we list only used ones — need full array size for
        # std::array member. StripClassProfile uses std::array with fixed size — must
        # zero-fill remaining.)
        for _ in range(len(points), MAX_POINTS):
            lines.append("            TemplatePoint{},")
        lines.append("        }},")
        lines.append(f"        /*polygon_count=*/{len(polygon)},")
        lines.append("        /*polygon=*/{{")
        for vertex in polygon:
            x, y = float(vertex[0]), float(vertex[1])
            lines.append(f"            PointF{{{cpp_float(x)}, {cpp_float(y)}}},")
        for _ in range(len(polygon), MAX_POLYGON):
            lines.append("            PointF{},")
        lines.append("        }},")
        lines.append("    },")

    lines += [
        "}};",
        "",
        "[[nodiscard]] inline constexpr std::size_t fixed_profile_index(FixedProfileId id) noexcept {",
        "    return static_cast<std::size_t>(id);",
        "}",
        "",
        "}  // namespace hzzs::vision_v2",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--json", type=Path, default=DEFAULT_JSON)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if output differs from generated content",
    )
    args = parser.parse_args()

    data = json.loads(args.json.read_text(encoding="utf-8"))
    text = render_header(data)

    if args.check:
        if not args.out.is_file():
            print(f"missing generated header: {args.out}", file=sys.stderr)
            return 1
        existing = args.out.read_text(encoding="utf-8")
        if existing != text:
            print(f"generated header out of date: {args.out}", file=sys.stderr)
            print("run: python tools/vision_v2/generate_fixed_profiles_inc.py", file=sys.stderr)
            return 1
        print(f"up to date: {args.out}")
        return 0

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {args.out} ({len(PROFILE_ORDER)} profiles)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
